package com.bpmn2example.orderfulfillmentandprocurement;

import org.kie.api.runtime.KieSession;
import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class MySendTaskHandler implements java.io.Serializable,WorkItemHandler {

KieSession k = null;
public MySendTaskHandler(KieSession ksession){
    this.k=ksession;
}


    static final long serialVersionUID = 1L;

     public void executeWorkItem(WorkItem workItem, WorkItemManager manager) {
        Boolean message = (Boolean) workItem.getParameter("Message");
        System.out.println("+++"+k);
        k.signalEvent("Message-orderreceived", message);
        // System.out.println("Sending message: {}"+message);
        manager.completeWorkItem(workItem.getId(), null);
    }

    public void abortWorkItem(WorkItem workItem, WorkItemManager manager) {
        // Do nothing, cannot be aborted
    }


}